// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vxobhvbcfoystjnkauqd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ4b2JodmJjZm95c3RqbmthdXFkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyNTc1MTIsImV4cCI6MjA2NzgzMzUxMn0.vYBRYYFscN1x2_9Pztqclyp22ozpwYwzPq4gXmmaFJQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});